apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "azure-adls-terraform-sp"
          valueMap:
            ARM_CLIENT_ID: ""
            ARM_CLIENT_SECRET: ""
            ARM_SUBSCRIPTION_ID: ""
            ARM_TENANT_ID: ""
            PRINCIPAL_MAPPING_TENANT_ID: ""
            PRINCIPAL_MAPPING_CLIENT_ID: ""
            PRINCIPAL_MAPPING_CLIENT_SECRET: ""
