apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: witboost-addons-adls-storage-es
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreType | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecrets.secretStore }} # Must match SecretStore on the cluster

  target:
    name: azure-adls-terraform-sp # Name for the secret to be created on the cluster
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.extractKey }}